steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$SHORT_SHA --build-arg DOPPLER_TOKEN_ARG=$$DOPPLER_TOKEN -f Dockerfile .' ]
    secretEnv: ['DOPPLER_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$SHORT_SHA']

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ['-c', 'gcloud run deploy ${_IMAGE_NAME_}-prod --image gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$SHORT_SHA --region us-central1 --allow-unauthenticated']

substitutions:
  _IMAGE_NAME_: ##TODO: [DEVELOPER SIDE] put a string that represents your app, spaces not allowed slug ex. ea-us-model-prod

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DOPPLER_TOKEN_PRODUCTION/versions/latest
      env: 'DOPPLER_TOKEN'

options:
    substitution_option: 'ALLOW_LOOSE'

images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$SHORT_SHA']